name: Download and Release

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'The URL of the file to download'
        required: true
permissions:
  contents: write
jobs:
  download_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract file name from URL
      id: extract_filename
      run: |
        echo "::set-output name=filename::$(basename ${{ github.event.inputs.file_url }})"

    - name: Get current date
      id: get_date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Create download directory
      run: mkdir -p download
    - name: Download file
      run: |
        curl -L ${{ github.event.inputs.file_url }} -o download/${{ steps.extract_filename.outputs.filename }}

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: "UploadAt-${{ steps.get_date.outputs.date }}"
        name: "Upload  ${{ steps.extract_filename.outputs.filename }}"
        body: 'Download ${{ steps.extract_filename.outputs.filename }}'
        artifacts: download/*
